name = "upgradeable-proxy"
version = "<%= package.version %>"
description = "Upgradeable UUPS Proxy package"

# `salt` here only affects proxy contract
[setting.salt]
description = "Change this to a unique string when deploying multiple instances of the system. Note that only the proxy contract will be unique."
defaultValue = "main"

# Override this setting in your own cannonfile to replace the implementation address with your contract address
[setting.implementation]
description = "Address of the implementation contract"
defaultValue = "0x5c3b576B95fb903f022Ce3E33938EB79F69B5745"

[setting.owner]
description = "Admin user for the system"
defaultValue = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[contract.Proxy]
artifact = "Proxy"
args = ["<%= settings.implementation %>", "<%= settings.owner %>"]
salt = "<%= settings.salt %>"
create2 = true
