name = "oz-uups-proxy"
version = "<%= package.version %>"
description = "Generic UUPS Proxy package using openzeppelins proxy contracts"

# `salt` here only affects proxy contract
[setting.salt]
description = "Change this to a unique string when deploying multiple instances of the system. Note that only the proxy contract will be unique."
defaultValue = "main"

# Override this setting in your own cannonfile to replace the implementation address with your own implementation contract address
[setting.implementation]
description = "Address of the implementation contract"
defaultValue = "0x5c3b576B95fb903f022Ce3E33938EB79F69B5745"

[setting.admin]
description = "Admin user for the system"
defaultValue = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[deploy.EmptyContract]
artifact = "EmptyContract"

[contract.Proxy]
artifact = "UUPSProxy"
args = [
  "<%= contracts.EmptyContract.address %>",
]
salt = "<%= settings.salt %>"
create2 = true
depends = [ "deploy.EmptyContract" ]

[invoke.upgrade_proxy_implementation]
target = ["Proxy"]
fromCall.func = "owner"
abi = "UUPSProxy"
func = "upgradeTo"
args = ["<%= settings.implementation %>"]
factory.UpgradedProxy.abiOf = ["UUPSProxy"]
factory.UpgradedProxy.event = "Upgraded"
factory.UpgradedProxy.arg = 0
factory.UpgradedProxy.highlight = true